"""empty message

Revision ID: f4cf4b8afcc7
Revises: 44afb9ea33fc
Create Date: 2024-10-11 16:06:20.868990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4cf4b8afcc7'
down_revision = '44afb9ea33fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.drop_index('inspection_ibfk_1')

    op.drop_table('inspection')
    op.drop_table('violation')
    op.drop_table('food_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('expiration_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('violation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('severity', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], name='violation_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inspection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('food_item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inspection_date', mysql.DATETIME(), nullable=True),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', mysql.FLOAT(), nullable=True),
    sa.Column('results', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], name='fk_food_item_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.create_index('inspection_ibfk_1', ['food_item_id'], unique=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
